# site settings
title: Open Data Boot Camp 2015
# email: hi@codeforcroatia.org
description: "Open Data Boot Camp is a youth camp focusing on use and reuse of public sector information organized by the Council for the OGP in Croatia."
baseurl: "http://dev.codeforcroatia.org/odbc"
# "http://codeforcroatia.org"
twitter_username: codeforcroatia
github_username:  codeforcroatia
analytics: 'UA-60198109-x'

# build settings
markdown: kramdown
