# site settings
title: Open Data Youth Camp 2015
# email: hi@codeforcroatia.org
description: "Open Data Youth Camp is a OGP youth camp focusing on use and reuse of public sector information organized by the Council for the OGP in Croatia."
baseurl: "http://odyc.codeforcroatia.org/2015/"
# "http://codeforcroatia.org"
twitter_username: codeforcroatia
github_username:  codeforcroatia
analytics: 'UA-60198109-x'

# build settings
markdown: kramdown
